"""Pure helpers for our OAuth 2.1 Authorization Server (no I/O).

The MCP client authenticates against us; we delegate the actual login to the
upstream provider. These helpers cover PKCE, opaque tokens, the deterministic
tenant id derived from the upstream account, and validation of Dynamic Client
Registration requests. I/O lives in infrastructure and the transport.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets
import uuid
from typing import Annotated, Literal
from urllib.parse import urlparse

from pydantic import BaseModel, ConfigDict, Field, StringConstraints, field_validator

from .consent import safe_hostname

# Stable namespace so the same upstream account always maps to the same tenant uuid.
# Unique per server (regenerated by the scaffold): two MCP servers must not share tenant
# ids for the same human, or an Upstash key collision becomes a tenant collision.
_TENANT_NAMESPACE = uuid.UUID("00000000-0000-4000-8000-0000b0075742")

_LOCAL_HOSTNAMES = frozenset({"localhost", "127.0.0.1", "[::1]", "::1"})
_MAX_REDIRECT_URIS = 10
_MAX_URI_LENGTH = 2048


def new_opaque_token(n_bytes: int = 32) -> str:
    """A high-entropy URL-safe opaque token (auth code, refresh token, state)."""
    return secrets.token_urlsafe(n_bytes)


def pkce_pair() -> tuple[str, str]:
    """``(code_verifier, code_challenge)`` for PKCE S256."""
    verifier = secrets.token_urlsafe(64)
    return verifier, _s256(verifier)


def verify_pkce_s256(verifier: str, challenge: str) -> bool:
    """Constant-time check that ``challenge == base64url(sha256(verifier))``."""
    if not verifier or not challenge:
        return False
    return hmac.compare_digest(_s256(verifier), challenge)


def _s256(verifier: str) -> str:
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def tenant_id_for_subject(upstream_subject: str) -> str:
    """Deterministic tenant uuid for an upstream account id."""
    return str(uuid.uuid5(_TENANT_NAMESPACE, upstream_subject))


def is_allowed_redirect_uri(uri: str) -> bool:
    """https anywhere, or http only on loopback (native/CLI MCP clients).

    The host must be a DNS name or an IP literal: the redirect is shown on the consent
    screen and its origin goes into a CSP header.
    """
    parsed = urlparse(uri)
    try:
        parsed.port  # noqa: B018 - raises ValueError on a malformed port
    except ValueError:
        return False
    if parsed.fragment or not parsed.netloc or not safe_hostname(parsed.hostname):
        return False
    if parsed.scheme == "https":
        return True
    return parsed.scheme == "http" and (parsed.hostname or "") in _LOCAL_HOSTNAMES


RedirectUri = Annotated[str, StringConstraints(min_length=1, max_length=_MAX_URI_LENGTH)]
GrantType = Literal["authorization_code", "refresh_token"]
_DEFAULT_GRANTS: tuple[GrantType, ...] = ("authorization_code", "refresh_token")


class ClientRegistration(BaseModel):
    """A validated RFC 7591 Dynamic Client Registration request.

    Every client is registered as public (``token_endpoint_auth_method="none"``,
    PKCE mandatory) whatever it asks for: a requested secret-based method is ignored
    rather than rejected, because MCP clients differ and the server never issues
    client secrets anyway (RFC 7591 lets the server override client metadata).
    """

    model_config = ConfigDict(extra="ignore")

    redirect_uris: list[RedirectUri] = Field(min_length=1, max_length=_MAX_REDIRECT_URIS)
    client_name: Annotated[str, StringConstraints(max_length=200)] | None = None
    grant_types: list[GrantType] = Field(
        default_factory=lambda: list(_DEFAULT_GRANTS), max_length=len(_DEFAULT_GRANTS)
    )

    @field_validator("redirect_uris")
    @classmethod
    def _redirects_are_safe(cls, uris: list[str]) -> list[str]:
        for uri in uris:
            if not is_allowed_redirect_uri(uri):
                raise ValueError("redirect_uris must be https (or http on loopback).")
        return uris
